# -*- coding: utf-8 -*-
"""MixlTup Marketing Plan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CuKu_1Ptbp0nXudXm9Lcw-HLfGpRxk-

# Membaca Data
"""

!wget https://raw.githubusercontent.com/angga5165/Data-Science-/main/Case_Study_2_MixlTup.csv

import pandas as pd
df = pd.read_csv("Case_Study_2_MixlTup.csv",sep=';')
df.head()

# Importing Modules untuk Notebook ini
import warnings; warnings.simplefilter('ignore')
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd, seaborn as sns
from sklearn import cluster, datasets
from sklearn.metrics import silhouette_score as siluet
from sklearn.metrics.cluster import homogeneity_score as purity
from sklearn.metrics import normalized_mutual_info_score as NMI

sns.set(style="ticks", color_codes=True)
random_state = 99

"Done"

"""# Cek Info Data"""

df.info()

df.describe()

"""ada keanehan di kolom skor pengeluaran dab promo, karena skor pengeluaran hanya sampai 100 dan untuk promo juga harusnya sampai 4, sedangkan didata ini skor pengeluaran sampai 101 dan promo 5

# Cek Nilai Unik Tiap Variabel
"""

df['Jenis Kelamin'].unique()

df['Jenis Kelamin'].value_counts()

df['Umur'].unique()

df['Umur'].value_counts()

df[df['Umur']==2]

df['skor-pengeluaran'].unique()

df['skor-pengeluaran'].value_counts()

df[df['skor-pengeluaran']==101]

df['Menikah'].unique()

df['Menikah'].value_counts()

df['Kota'].unique()

df['Kota'].value_counts()

df['Promo'].unique()

df['Promo'].value_counts()

df[df['Promo']==5]

df['HariFav'].unique()

df['HariFav'].value_counts()

df['FavFlavor'].unique()

df['FavFlavor'].value_counts()

"""# Menangani Noise"""

avg_skor_wanita = df[df['Jenis Kelamin'] == 'Wanita']['skor-pengeluaran'].mean()
avg_skor_pria = df[df['Jenis Kelamin'] == 'Pria']['skor-pengeluaran'].mean()

avg_skor_pria, avg_skor_wanita

df[df['Jenis Kelamin'] == '-']

# Hitung rata-rata skor per jenis kelamin
avg_skor_pria = df.loc[df['Jenis Kelamin'] == 'Pria', 'skor-pengeluaran'].mean()
avg_skor_wanita = df.loc[df['Jenis Kelamin'] == 'Wanita', 'skor-pengeluaran'].mean()

# Loop untuk isi baris kosong atau '-'
for idx, row in df[df['Jenis Kelamin'].isin(['-', None, ''])].iterrows():
    skor_target = row['skor-pengeluaran']
    if abs(skor_target - avg_skor_pria) < abs(skor_target - avg_skor_wanita):
        df.at[idx, 'Jenis Kelamin'] = 'Pria'
    else:
        df.at[idx, 'Jenis Kelamin'] = 'Wanita'

df['Jenis Kelamin'].unique()

df['Jenis Kelamin'] = df['Jenis Kelamin'].replace('-', 'Wanita')
df['Jenis Kelamin'].unique()

df = df.replace({'Umur': {"35'": 35, "2": 20},
    'Menikah': {'-': '0', ' ': '0', '': '0'},
    'Kota': {'JJakarta': 'Jakarta'},
    'Promo': {5: 3},
    'skor-pengeluaran': {101: 100}
})

df['Jenis Kelamin'].value_counts()

df['Umur'].value_counts()

df['Menikah'].value_counts()

df['Kota'].value_counts()

"""# Cek Missing Value"""

# Hitung persentase missing value
null_percent = (df.isnull().sum() / len(df)) * 100

# Buat jadi DataFrame biar tampil rapi
null_percent_df = pd.DataFrame({"Missing (%)": null_percent.round(2)})
display(null_percent_df)

null_count = pd.DataFrame({"Missing": df.isnull().sum()})
display(null_count)

"""# Menangani Missing Value"""

df['Jenis Kelamin'].value_counts()

df['Jenis Kelamin'].unique()

skor_target1 = df.loc[df['Jenis Kelamin'].isna(), 'skor-pengeluaran'].iloc[0]

if abs(skor_target1 - avg_skor_pria) < abs(skor_target1 - avg_skor_wanita):
    imputasi = 'Pria'
else:
    imputasi = 'Wanita'

print("Jenis kelamin yang diimputasi:", imputasi)

df['Jenis Kelamin'] = df['Jenis Kelamin'].fillna('Pria')
df['Jenis Kelamin'].unique()

df['Menikah'].value_counts()

df['Menikah'] = df['Menikah'].fillna(df['Menikah'].mode()[0])

df['Promo'].value_counts()

df['Promo'] = df['Promo'].fillna(df['Promo'].mode()[0])

"""# Cek Missing Value Setelah Penanganan"""

# Hitung persentase missing value
null_percent = (df.isnull().sum() / len(df)) * 100

# Buat jadi DataFrame biar tampil rapi
null_percent_df = pd.DataFrame({"Missing (%)": null_percent.round(2)})
display(null_percent_df)

null_count = pd.DataFrame({"Missing": df.isnull().sum()})
display(null_count)

"""# Mengubah Tipe Data"""

# Bersihkan kolom 'Pendapatan-per-bulan' dari teks dan ubah jadi integer
df['Pendapatan-per-bulan'] = (
    df['Pendapatan-per-bulan']
    .str.replace('Rp', '', regex=False)  # hapus tulisan 'Rp'
    .str.replace('.', '', regex=False)   # hapus tanda titik
    .astype(float)                       # ubah ke float (bisa juga int)
)

# Cek hasil
df[['Pendapatan-per-bulan']].head()

df = df.astype({
    'ID': 'int64',
    'Jenis Kelamin': 'category',
    'Umur': 'int64',
    'skor-pengeluaran': 'float64',
    'Menikah': 'int64',
    'Kota': 'category',
    'Promo': 'int64',
    'HariFav': 'category',
    'FavFlavor': 'category'
})

df.head()

df.describe()

"""ada sebuah keanehan di pendapatan-per-bulan dengan nilai 0"""

df[df['Pendapatan-per-bulan']==0]

"""# Cek Distribusi Data Numerik"""

fig, axes = plt.subplots(1, 3, figsize=(20, 5), sharey=False)
sns.histplot(df['Umur'], ax=axes[0])
sns.histplot(df['Pendapatan-per-bulan'], ax=axes[1])
sns.histplot(df['skor-pengeluaran'], ax=axes[2])
plt.show()

# Bikin figure
plt.figure(figsize=(20, 4))

# Plot 1
plt.subplot(1, 3, 1)
sns.boxplot(x="Umur", data=df)
plt.title("Distribusi Umur - df")

# Plot 2
plt.subplot(1, 3, 2)
sns.boxplot(x="Pendapatan-per-bulan", data=df)
plt.title("Distribusi Pendapatan - df")

# Plot 3
plt.subplot(1, 3, 3)
sns.boxplot(x="skor-pengeluaran", data=df)
plt.title("Distribusi skor-pengeluaran - df")

"""# Menangani Outlier"""

# Mengecek banyaknya outlier pada dataset Jakarta
Q1_Pendapatan = df['Pendapatan-per-bulan'].quantile(0.25)
Q2_Pendapatan = df['Pendapatan-per-bulan'].quantile(0.50)
Q3_Pendapatan = df['Pendapatan-per-bulan'].quantile(0.75)
IQR_Pendapatan = Q3_Pendapatan - Q1_Pendapatan
outlier_Pendapatan = (df['Pendapatan-per-bulan'] <= Q1_Pendapatan - 1.5*IQR_Pendapatan) | (df['Pendapatan-per-bulan'] >= Q3_Pendapatan + 1.5*IQR_Pendapatan)
print("Banyaknya outlier = ",sum(outlier_Pendapatan))

df_outlier = df[
    (df['Pendapatan-per-bulan'] <= Q1_Pendapatan - 1.5 * IQR_Pendapatan) |
    (df['Pendapatan-per-bulan'] >= Q3_Pendapatan + 1.5 * IQR_Pendapatan)
]
df_outlier

# Data non-outlier
df = df[~outlier_Pendapatan]

# Bikin figure
plt.figure(figsize=(20, 4))

# Plot 1
plt.subplot(1, 3, 1)
sns.boxplot(x="Umur", data=df)
plt.title("Distribusi Umur - df")

# Plot 2
plt.subplot(1, 3, 2)
sns.boxplot(x="Pendapatan-per-bulan", data=df)
plt.title("Distribusi Pendapatan - df")

# Plot 3
plt.subplot(1, 3, 3)
sns.boxplot(x="skor-pengeluaran", data=df)
plt.title("Distribusi skor-pengeluaran - df")

df.describe()

df

"""# Visualisasi"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membuat plot dengan ukuran besar
plt.figure(figsize=(18, 4))

# Pie chart untuk 'Jenis Kelamin'
plt.subplot(1, 3, 1)
df['Jenis Kelamin'].value_counts().plot.pie(autopct='%1.1f%%', colors=['#FF9999','#66B3FF'])
plt.title('Proporsi Jenis Kelamin')

# Pie chart untuk 'Menikah'
plt.subplot(1, 3, 2)
df['Menikah'].value_counts().plot.pie(autopct='%1.1f%%', colors=['#FFCC99','#99FF99'])
plt.title('Proporsi Status Menikah')

# Membuat countplot untuk 'Kota'
plt.subplot(1, 3, 3)
df['Kota'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Proporsi Kota')

# Mengatur layout agar tidak saling tumpang tindih
plt.tight_layout()

# Menampilkan plot
plt.show()

# Membuat plot dengan ukuran besar
plt.figure(figsize=(16, 4))

# Membuat countplot untuk 'Promo'
plt.subplot(1, 3, 1)
sns.countplot(x='Promo', data=df, palette='Set3')
plt.title('Distribusi Promo')

# Membuat countplot untuk 'HariFav'
plt.subplot(1, 3, 2)
sns.countplot(x='HariFav', data=df, palette='viridis')
plt.title('Distribusi Hari Favorit')

# Membuat countplot untuk 'FavFlavor'
plt.subplot(1, 3, 3)
sns.countplot(x='FavFlavor', data=df, palette='Set1')
plt.title('Distribusi Rasa Favorit')

# Mengatur layout agar tidak saling tumpang tindih
plt.tight_layout()

# Menampilkan plot
plt.show()

# Boxplot for each variable
plt.figure(figsize=(15, 6))

plt.subplot(2, 3, 1)
sns.boxplot(y='Umur', data=df)
plt.title('Boxplot of Umur')

plt.subplot(2, 3, 2)
sns.boxplot(y='Pendapatan-per-bulan', data=df)
plt.title('Boxplot of Pendapatan-per-bulan')

plt.subplot(2, 3, 3)
sns.boxplot(y='skor-pengeluaran', data=df)
plt.title('Boxplot of Skor Pengeluaran')

plt.subplot(2, 3, 4)
sns.histplot(df['Umur'], kde=True)
plt.title('Displot of Umur')

plt.subplot(2, 3, 5)
sns.histplot(df['Pendapatan-per-bulan'], kde=True)
plt.title('Displot of Pendapatan-per-bulan')

plt.subplot(2, 3, 6)
sns.histplot(df['skor-pengeluaran'], kde=True)
plt.title('Displot of Skor Pengeluaran')

plt.tight_layout()
plt.show()

"""# Insight Awal

Proporsi Demografis
- Jenis Kelamin: Mayoritas pelanggan adalah wanita (57,7%), sedangkan pria berjumlah 42,3%.
→ Artinya, strategi pemasaran bisa mempertimbangkan pendekatan yang lebih relevan untuk konsumen wanita.

- Status Menikah: Sebagian besar pelanggan sudah menikah (86,7%), sementara yang belum menikah hanya 13,3%.
→ Indikasi bahwa segmen pelanggan didominasi oleh kelompok usia dewasa dan mapan.

- Kota Asal: Pelanggan tersebar di tiga kota utama, dengan Jakarta (44,4%) sebagai penyumbang terbanyak, diikuti Depok (29,1%) dan Tangerang (26,5%).
→ Distribusi ini menunjukkan potensi pasar terbesar berada di Jakarta.

Distribusi Promo, Hari Favorit, dan Rasa Favorit

- Promo: Kategori promo 1(jarang) paling sering digunakan oleh pelanggan, menunjukkan efektivitas promosi tipe tersebut.

- Hari Favorit: Senin dan Sabtu menjadi hari paling ramai transaksi, sedangkan Kamis dan Rabu paling sepi.
→ Bisa jadi karena pelanggan berbelanja di awal minggu (stok baru) dan akhir pekan (libur).

- Rasa Favorit: Tidak terdapat rasa yang mendominasi secara signifikan, namun rasa Vanilla (kode 0) tampak sedikit lebih populer dibandingkan rasa lainnya.
→ Kondisi ini menunjukkan bahwa selera pelanggan cukup beragam, sehingga penting untuk mempertahankan variasi produk agar tetap relevan dengan preferensi konsumen.

Distribusi Numerik (Umur, Pendapatan, Skor Pengeluaran)

- Umur: Rentang umur pelanggan berkisar antara 19–60 tahun, dengan mayoritas di sekitar 30–40 tahun.
→ Menunjukkan target utama adalah konsumen usia produktif.

- Pendapatan per Bulan: Sebagian besar pelanggan memiliki pendapatan sekitar 15–30 juta rupiah, namun ada beberapa outlier berpendapatan sangat tinggi.

- Skor Pengeluaran: Distribusi cukup merata, tetapi cenderung tinggi (rata-rata 50–60).
→ Artinya pelanggan umumnya aktif berbelanja, potensi customer retention cukup besar.

# Clustering Analisis
"""

sns.pairplot(df, hue='Kota')

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='Pendapatan-per-bulan', y='skor-pengeluaran', hue='Kota', palette='Set2')
plt.title('Scatter Plot: Pendapatan vs Skor Pengeluaran per Kota')
plt.xlabel('Pendapatan per bulan (Rp)')
plt.ylabel('Skor Pengeluaran')
plt.show()

sns.pairplot(df, vars=['Umur','Pendapatan-per-bulan','skor-pengeluaran'], hue='Kota', palette='Set2', diag_kind='kde')
plt.suptitle('Pairplot: Umur, Pendapatan, Skor Pengeluaran', y=1.02)
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(data=df, x='Kota', y='skor-pengeluaran', palette='Pastel1')
plt.title('Boxplot Skor Pengeluaran per Kota')
plt.xlabel('Kota')
plt.ylabel('Skor Pengeluaran')
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(data=df, x='Jenis Kelamin', y='Pendapatan-per-bulan', palette='Pastel2')
plt.title('Boxplot Pendapatan per Jenis Kelamin')
plt.xlabel('Jenis Kelamin')
plt.ylabel('Pendapatan per bulan (Rp)')
plt.show()

"""Berdasarkan visualisasi awal yang ditampilkan dalam scatter plot, pairplot, dan boxplot, terlihat adanya pola yang cukup jelas untuk melakukan clustering pada data ini. Scatter plot menunjukkan distribusi pendapatan per bulan dan skor pengeluaran yang berbeda di tiap kota, dengan Depok memiliki skor pengeluaran tinggi dan pendapatan yang bervariasi, Jakarta cenderung memiliki pendapatan menengah dengan skor pengeluaran sedang, serta Tangerang yang memiliki skor pengeluaran rendah dan pendapatan yang relatif rendah juga. Pairplot memperlihatkan hubungan antara umur, pendapatan, dan skor pengeluaran dengan pewarnaan berdasarkan kota, yang mengindikasikan adanya pemisahan kelompok yang cukup nyata antar kota, terutama pada variabel skor pengeluaran. Boxplot memperkuat observasi ini dengan menunjukkan distribusi skor pengeluaran yang berbeda signifikan antar kota, dimana Depok memiliki median pengeluaran tertinggi, Jakarta di tengah, dan Tangerang yang paling rendah serta lebih banyak outlier. Dari pola-pola ini, dapat disimpulkan bahwa variabel-variabel tersebut berpotensi membentuk cluster yang jelas jika dilakukan analisis clustering lebih lanjut, dan clustering berdasarkan kota dapat membantu dalam memahami segmentasi perilaku pendapatan dan pengeluaran masyarakat di masing-masing wilayah.

##  scaler untuk clustering
"""

from sklearn.preprocessing import StandardScaler
cols = ['Umur', 'Pendapatan-per-bulan', 'skor-pengeluaran']
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[cols] = scaler.fit_transform(df[cols])

X = df_scaled[['Umur', 'skor-pengeluaran', 'Pendapatan-per-bulan']]#.values

distorsions, k1, kN = [], 2, 10
for k in range(k1, kN):
    kmeans = cluster.KMeans(n_clusters=k, random_state=80).fit(X)
    distorsions.append(kmeans.inertia_)

plt.plot(range(k1, kN), distorsions); plt.grid(True)
plt.title('Elbow curve')

# k-means++ clustering http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
k=4
kmPP = cluster.KMeans(n_clusters=k, random_state=80, init='k-means++')
kmPP.fit(X)
C_kmpp = kmPP.predict(X)

sns.countplot(x=C_kmpp)
C_kmpp[:10]

df_scaled['k-means++'] = C_kmpp
g = sns.pairplot(df_scaled[['Umur','Pendapatan-per-bulan','skor-pengeluaran','k-means++']], \
                 hue="k-means++", diag_kind="hist", palette="tab10")

df_scaled

sns.countplot(x='k-means++', data=df_scaled)

df['kmeans++'] = df_scaled['k-means++']

df

from sklearn.metrics import silhouette_score
# 3️⃣ Evaluasi dengan Silhouette Score
sil_score = silhouette_score(X, C_kmpp)
print(f"Silhouette Score: {sil_score:.3f}")

"""## Hasil Cluster"""

df.groupby('kmeans++')[['Umur','Pendapatan-per-bulan','skor-pengeluaran']].mean().round(2)

"""Cluster 0 → 🟢 Young – Low Income – High Spender

Usia muda, penghasilan kecil, tapi konsumsi tinggi. Cenderung impulsif dan mudah terpengaruh promo.

Cluster 1 → 🔵 Adult – High Income – Very High Spender

Dewasa muda, mapan secara finansial, suka belanja premium dan loyal terhadap brand.

Cluster 2 → 🟣 Mature – High Income – Low Spender

Dewasa matang, berpenghasilan tinggi tapi hemat. Fokus pada kebutuhan, bukan gaya hidup.

Cluster 3 → 🟠 Older – Medium Income – Moderate Spender

Usia tua, pendapatan menengah, belanja secukupnya dan cenderung rasional.
"""

#cluster 3
dfclus3 = df[df["kmeans++"]==3]
usia = dfclus3["Umur"]
pendapatan = dfclus3["Pendapatan-per-bulan"]
skor = dfclus3["skor-pengeluaran"]
rating = dfclus3["Promo"]

# Set up the figure for histograms and countplot
fig, axs = plt.subplots(2, 2, figsize=(12, 10))

# Histogram for Usia
sns.histplot(usia, bins=5, kde=False, ax=axs[0, 0], color='lightblue')
axs[0, 0].set_title('Histogram Usia')
axs[0, 0].set_xlabel('Usia')
axs[0, 0].set_ylabel('Frekuensi')

# Histogram for Pendapatan
sns.histplot(pendapatan, bins=5, kde=False, ax=axs[0, 1], color='lightgreen')
axs[0, 1].set_title('Histogram Pendapatan')
axs[0, 1].set_xlabel('Pendapatan')
axs[0, 1].set_ylabel('Frekuensi')

# Histogram for Skor
sns.histplot(skor, bins=5, kde=False, ax=axs[1, 0], color='lightcoral')
axs[1, 0].set_title('Histogram Skor')
axs[1, 0].set_xlabel('Skor pengeluaran')
axs[1, 0].set_ylabel('Frekuensi')

# Countplot for Rating
sns.countplot(x=rating, ax=axs[1, 1], palette='light:#5A9')
axs[1, 1].set_title('Countplot Rating')
axs[1, 1].set_xlabel('Promo')
axs[1, 1].set_ylabel('Frekuensi')

# Adjust layout
plt.tight_layout()
plt.show()

"""Insight Potensial Strategi:

* Fokus pasar: Konsumen usia menengah dengan daya beli mapan.

* Pendekatan pemasaran dapat diarahkan pada nilai (value driven), bukan hanya sekadar diskon.

* Program loyalitas, bonus eksklusif, atau membership berpotensi lebih efektif dibanding promo intensif.

* Ada peluang untuk meningkatkan pengeluaran rata-rata melalui bundling produk atau penawaran premium.

Implikasi Bi
"""

#cluster 2
dfclus2 = df[df["kmeans++"]==2]
usia = dfclus2["Umur"]
pendapatan = dfclus2["Pendapatan-per-bulan"]
skor = dfclus2["skor-pengeluaran"]
rating = dfclus2["Promo"]

# Set up the figure for histograms and countplot
fig, axs = plt.subplots(2, 2, figsize=(12, 10))

# Histogram for Usia
sns.histplot(usia, bins=5, kde=False, ax=axs[0, 0], color='lightblue')
axs[0, 0].set_title('Histogram Usia')
axs[0, 0].set_xlabel('Usia')
axs[0, 0].set_ylabel('Frekuensi')

# Histogram for Pendapatan
sns.histplot(pendapatan, bins=5, kde=False, ax=axs[0, 1], color='lightgreen')
axs[0, 1].set_title('Histogram Pendapatan')
axs[0, 1].set_xlabel('Pendapatan')
axs[0, 1].set_ylabel('Frekuensi')

# Histogram for Skor
sns.histplot(skor, bins=5, kde=False, ax=axs[1, 0], color='lightcoral')
axs[1, 0].set_title('Histogram Skor')
axs[1, 0].set_xlabel('Skor pengeluaran')
axs[1, 0].set_ylabel('Frekuensi')

# Countplot for Rating
sns.countplot(x=rating, ax=axs[1, 1], palette='light:#5A9')
axs[1, 1].set_title('Countplot Rating')
axs[1, 1].set_xlabel('Promo')
axs[1, 1].set_ylabel('Frekuensi')

# Adjust layout
plt.tight_layout()
plt.show()

"""Interpretasi Strategis:

* Segmentasi usia dan pendapatan menunjukkan pasar yang potensial dan stabil.

* Tingginya frekuensi penggunaan promo pada segmen ini menandakan bahwa strategi promosi sangat efektif untuk mendorong transaksi.

* Masih terdapat celah peningkatan pengeluaran, sehingga program promosi dapat diarahkan bukan hanya untuk menarik pengguna, tetapi juga untuk mendorong mereka meningkatkan nilai transaksi (upselling atau bundling).

Implikasi Bisnis:
Strategi yang paling relevan adalah promosi yang bersifat value-oriented seperti paket hemat, bundling premium, atau poin loyalitas yang mendorong konsumen dengan daya beli tinggi namun pengeluaran moderat untuk bertransaksi lebih besar secara konsisten.
"""

#cluster 1
dfclus1 = df[df["kmeans++"]==1]
usia = dfclus1["Umur"]
pendapatan = dfclus1["Pendapatan-per-bulan"]
skor = dfclus1["skor-pengeluaran"]
rating = dfclus1["Promo"]

# Set up the figure for histograms and countplot
fig, axs = plt.subplots(2, 2, figsize=(12, 10))

# Histogram for Usia
sns.histplot(usia, bins=5, kde=False, ax=axs[0, 0], color='lightblue')
axs[0, 0].set_title('Histogram Usia')
axs[0, 0].set_xlabel('Usia')
axs[0, 0].set_ylabel('Frekuensi')

# Histogram for Pendapatan
sns.histplot(pendapatan, bins=5, kde=False, ax=axs[0, 1], color='lightgreen')
axs[0, 1].set_title('Histogram Pendapatan')
axs[0, 1].set_xlabel('Pendapatan')
axs[0, 1].set_ylabel('Frekuensi')

# Histogram for Skor
sns.histplot(skor, bins=5, kde=False, ax=axs[1, 0], color='lightcoral')
axs[1, 0].set_title('Histogram Skor')
axs[1, 0].set_xlabel('Skor pengeluaran')
axs[1, 0].set_ylabel('Frekuensi')

# Countplot for Rating
sns.countplot(x=rating, ax=axs[1, 1], palette='light:#5A9')
axs[1, 1].set_title('Countplot Rating')
axs[1, 1].set_xlabel('Promo')
axs[1, 1].set_ylabel('Frekuensi')

# Adjust layout
plt.tight_layout()
plt.show()

"""Mayoritas responden berada di usia produktif sekitar 27–38 tahun dengan pendapatan menengah, menunjukkan bahwa mereka adalah konsumen aktif dan potensial dalam hal belanja. Skor pengeluaran yang cukup tinggi (umumnya antara 70–90) memperkuat fakta bahwa mereka bukan hanya mampu, tetapi juga aktif dalam melakukan pembelian. Namun, menariknya, penggunaan promo masih terbatas—terdapat kecenderungan “jarang” memanfaatkan penawaran, yang menunjukkan bahwa meskipun potensi besar ada, peluang untuk memaksimalkan engagement melalui strategi promosi belum terpenuhi. Dengan demikian, untuk mencapai hasil optimal, diperlukan pendekatan yang lebih personal, relevan dan segmented—baik melalui diskon, bundling, maupun program loyalitas yang dirancang khusus untuk segmen yang sudah aktif konsumsi tapi belum optimal dalam pemanfaatan promo."""

#cluster 0
dfclus0 = df[df["kmeans++"]==0]
usia = dfclus0["Umur"]
pendapatan = dfclus0["Pendapatan-per-bulan"]
skor = dfclus0["skor-pengeluaran"]
rating = dfclus0["Promo"]

# Set up the figure for histograms and countplot
fig, axs = plt.subplots(2, 2, figsize=(12, 10))

# Histogram for Usia
sns.histplot(usia, bins=5, kde=False, ax=axs[0, 0], color='lightblue')
axs[0, 0].set_title('Histogram Usia')
axs[0, 0].set_xlabel('Usia')
axs[0, 0].set_ylabel('Frekuensi')

# Histogram for Pendapatan
sns.histplot(pendapatan, bins=5, kde=False, ax=axs[0, 1], color='lightgreen')
axs[0, 1].set_title('Histogram Pendapatan')
axs[0, 1].set_xlabel('Pendapatan')
axs[0, 1].set_ylabel('Frekuensi')

# Histogram for Skor
sns.histplot(skor, bins=5, kde=False, ax=axs[1, 0], color='lightcoral')
axs[1, 0].set_title('Histogram Skor')
axs[1, 0].set_xlabel('Skor pengeluaran')
axs[1, 0].set_ylabel('Frekuensi')

# Countplot for Rating
sns.countplot(x=rating, ax=axs[1, 1], palette='light:#5A9')
axs[1, 1].set_title('Countplot Rating')
axs[1, 1].set_xlabel('Promo')
axs[1, 1].set_ylabel('Frekuensi')

# Adjust layout
plt.tight_layout()
plt.show()

"""Kesimpulan Strategis Umum

Audiens didominasi usia muda dengan pendapatan menengah dan pengeluaran aktif.

Promo saat ini belum optimal menarik perhatian — bukan karena tidak suka promo, tetapi karena promonya belum relevan atau kurang agresif.

Segmentasi potensial:

* Mass segment (skor pengeluaran sedang, jarang promo) → edukasi promo + bundle menarik

* Premium kecil (skor tinggi) → buat exclusive offer atau membership

* Promo-active segment (sering promo) → jadikan target campaign pertama untuk meningkatkan engagement

Insight: Walaupun mayoritas jarang pakai promo, mereka bukan anti-promo — artinya promosi yang lebih menarik atau personalisasi bisa meningkatkan engagement.
"""

import matplotlib.pyplot as plt

# Data
labels = ['Cluster 0', 'Cluster 1', 'Cluster 2', 'Cluster 3']

# Hitung proporsi tiap cluster
sizes = df['kmeans++'].value_counts(normalize=True) * 100
sizes = sizes.sort_index().round(1)

# Warna (boleh disesuaikan jika ingin mirip seperti gambar)
colors = ['#A7C7E7', '#6593B5', '#416788', '#274060']

# Membuat donut chart
fig, ax = plt.subplots(figsize=(6, 6), facecolor='white')
wedges, texts, autotexts = ax.pie(
    sizes,
    labels=None,            # Label di luar akan ditulis manual
    autopct='%1.1f%%',
    startangle=90,
    colors=colors,
    pctdistance=0.85,
    textprops={'color': 'white'}
)

# Tambahkan lingkaran putih di tengah untuk efek donut
centre_circle = plt.Circle((0, 0), 0.60, fc='white')
fig.gca().add_artist(centre_circle)

# Tambahkan legend di atas
plt.legend(
    wedges,
    labels,
    title="",
    loc="upper center",
    bbox_to_anchor=(0.5, 1.15),
    ncol=4,
    frameon=False,
    labelcolor='black'
)

# Membuat background hitam & styling
plt.setp(autotexts, size=12, weight="bold", color='white')
ax.set_facecolor('black')
plt.tight_layout()

plt.show()

"""Interpretasi Strategis

* Cluster 1 adalah segmentasi utama — karena memiliki porsi terbesar (32.6%), artinya pola perilaku/karakter yang dimiliki cluster ini mewakili sebagian besar responden.

* Cluster 2 juga cukup dominan (28.5%), sehingga karakternya masih penting untuk dianalisis sebagai second-tier behavior.

* Cluster 0 berada di tengah (20.7%), yang bisa menjadi kelompok transisi atau memiliki ciri khas moderat dibanding dua cluster teratas.

* Cluster 3 adalah kelompok paling kecil (18.1%), namun justru bisa menjadi kelompok paling unik atau niche, berpotensi menjadi target khusus jika dilakukan segmentasi berbasis personalisasi.

Kesimpulan :
Mayoritas responden terkonsentrasi di dua cluster utama (Cluster 1 dan 2), yang secara total mencakup lebih dari 60% populasi.
Cluster 3 sebagai kelompok paling kecil berpotensi memiliki karakteristik yang paling "berbeda" atau spesifik, sehingga penting jika ingin melakukan analisis mendalam atau strategi personalisasi.
"""

import matplotlib.pyplot as plt
import seaborn as sns


# Konfigurasi style agar mirip gambar
plt.style.use('dark_background')
sns.set_palette(['#A7C7E7', '#6593B5', '#416788', '#274060'])   # warna mirip contoh

# Membuat 2 subplot berdampingan
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# --- Plot 1: Countplot HariFav ---
sns.countplot(data=df, x='HariFav', hue='kmeans++', ax=axes[0])
axes[0].set_title("Countplot of HariFav", fontsize=12)
axes[0].set_xlabel("HariFav")
axes[0].set_ylabel("Count")
axes[0].legend(title='k-means++')

# --- Plot 2: Countplot Menikah ---
sns.countplot(data=df, x='Menikah', hue='kmeans++', ax=axes[1])
axes[1].set_title("Countplot of Menikah", fontsize=12)
axes[1].set_xlabel("Menikah")
axes[1].set_ylabel("Count")
axes[1].legend(title='k-means++')

plt.tight_layout()
plt.show()

"""Interpretasi Berdasarkan Hari Favorit (HariFav)

* Cluster 0 terlihat dominan memilih hari Senin, menunjukkan karakter individu yang mungkin lebih produktif atau semangat memulai minggu.
* Cluster 1 cenderung menyukai hari Sabtu dan Minggu, mengindikasikan preferensi terhadap waktu luang atau aktivitas santai (orientasi leisure/weekend lifestyle).
* Cluster 2 memiliki pola berbeda, dengan puncak pada hari Minggu dan Sabtu, tetapi tidak sekuat Cluster 1 — bisa jadi ini kelompok yang menikmati weekend tetapi tidak seintens cluster 1.
* Cluster 3 lebih banyak muncul pada hari Minggu dan Minggu, tetapi distribusinya lebih seimbang dibanding cluster lainnya — mengindikasikan preferensi campuran dan tidak terlalu spesifik.

Insight: → Preferensi hari libur (Sabtu–Minggu) menjadi pembeda kuat antara cluster 1 & 2 dibanding cluster 0 yang orientasinya "awal minggu". Ini bisa digunakan untuk strategi segmentasi aktivitas atau rekomendasi jadwal.

Interpretasi Berdasarkan Status Menikah

* Cluster 1 dan Cluster 2 didominasi oleh responden yang sudah menikah, menunjukkan karakteristik cluster ini mungkin terkait dengan gaya hidup keluarga.

* Cluster 3 juga memiliki mayoritas sudah menikah, tetapi tidak sekuat Cluster 1.

* Cluster 0 memiliki proporsi lebih besar pada status belum menikah (Tidak Menikah) dibanding cluster lainnya, menandakan profil yang mungkin masih lebih fleksibel atau independen dalam pola aktivitas.

Insight: → Status pernikahan menjadi ciri pemisah cluster yang signifikan: cluster yang menyukai weekend (Cluster 1 & 2) lebih banyak berasal dari individu yang sudah menikah — bisa jadi weekend dimanfaatkan untuk quality time keluarga.

Insight Strategis Potensial (jika untuk rekomendasi/tindakan)

* Cluster 0: cocok untuk promosi aktivitas produktif, event Senin–Jumat, atau campaign "Kickstart your week".

* Cluster 1: menunjukkan preferensi terhadap hari Sabtu dan Minggu, meskipun tren juga memperlihatkan peningkatan aktivitas pada hari Senin, sehingga dapat diarahkan pada strategi yang memadukan nuansa produktivitas dan waktu luang.

* Cluster 2: memiliki puncak preferensi pada hari Senin dan Sabtu, menandakan keseimbangan antara orientasi kerja dan rekreasi, sehingga cocok untuk promosi yang menjembatani aktivitas weekday dan weekend.

* Cluster 3: fleksibel, bisa diarahkan baik ke weekday maupun weekend dengan pendekatan general.

# EDA untuk MBA
"""

# Mapping kategori sesuai deskripsi kamu
flavor_map = {
    0: 'Vanilla',
    1: 'Strawberry',
    2: 'Cokelat',
    3: 'Blueberry',
    4: 'Bubblegum/Cottoncandy',
    5: 'Coconut',
    6: 'Caramel Pecan',
    7: 'Mix 2 Flavors',
    8: 'Mix 3 Flavors'
}

promo_map = {
    0: 'Tidak Pernah',
    1: 'Jarang',
    2: 'Sedang',
    3: 'Sering'
}

married_map = {
    0: 'Tidak Menikah',
    1: 'Menikah'
}

# Terapkan ke DataFrame
df['FavFlavor'] = df['FavFlavor'].map(flavor_map)
df['Promo'] = df['Promo'].map(promo_map)
df['Menikah'] = df['Menikah'].map(married_map)

df.head()

"""#MBA"""

# --- Pisahkan data untuk cluster 0 ---
cluster_0 = df[df['kmeans++'] == 0]

# --- Pilih kolom kategorikal ---
kolom_item = ['Jenis Kelamin', 'Kota', 'Promo', 'HariFav', 'FavFlavor']

# --- Bentuk keranjang per pelanggan ---
cluster_0['basket'] = cluster_0[kolom_item].values.tolist()

# --- Transaction Encoder ---
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_ary = te.fit(cluster_0['basket']).transform(cluster_0['basket'])
basket_0 = pd.DataFrame(te_ary, columns=te.columns_)

# --- Apriori dan association rules ---
frequent_0 = apriori(basket_0, min_support=0.05, use_colnames=True)
rules_0 = association_rules(frequent_0, metric="lift", min_threshold=1.1)
strong_rules_0 = rules_0[(rules_0['confidence'] >= 0.5) & (rules_0['lift'] >= 1.2)]

# --- Tampilkan aturan teratas ---
print("🟢 Cluster 0 – Aturan Asosiasi Terkuat:")
display(strong_rules_0.sort_values(by='lift', ascending=False).head(10))

# --- Kesimpulan otomatis ---
def interpret_rules(rules, cluster_name):
    if rules.empty:
        print(f"\n❌ Tidak ditemukan aturan kuat untuk {cluster_name}.")
        return
    print(f"\n📊 Kesimpulan {cluster_name}:")
    for _, row in rules.sort_values(by='lift', ascending=False).head(5).iterrows():
        antecedent = ', '.join(list(row['antecedents']))
        consequent = ', '.join(list(row['consequents']))
        print(f"- Jika pelanggan memiliki atribut [{antecedent}], maka kemungkinan besar juga memiliki [{consequent}] "
              f"(confidence={row['confidence']:.2f}, lift={row['lift']:.2f}).")

interpret_rules(strong_rules_0, "Cluster 0")

"""Interpretasi:

Pelanggan yang jarang atau tidak pernah mengikuti promo (Promo = Tidak Pernah)
justru terkonsentrasi di Depok, sering bertransaksi pada hari Selasa, dan menyukai rasa Vanilla.

Meskipun mereka bukan pengguna promo aktif, mereka masih aktif belanja di hari tertentu dengan rasa tertentu → perilaku spontan tapi teratur.

Lift > 8 berarti korelasi yang sangat kuat antara “Tidak Pernah Promo” dengan kombinasi Vanilla–Depok–Selasa → pola kebiasaan yang nyata.

💡 Insight & Rekomendasi Bisnis (Cluster 0):

🎯 Targetkan Depok – Vanilla – Hari Selasa.
Gunakan kampanye kecil seperti “Vanilla Tuesday” atau “Buy 1 Get 1 Vanilla on Tuesdays” untuk mengubah pelanggan non-promo menjadi pelanggan promo.

💬 Eksperimen promo ringan.
Karena mereka tergolong High Spender tapi Low Income, tawarkan promo hemat (contoh: diskon 10% atau cashback kecil).

🧋 Fokus rasa populer.
Rasa Vanilla bisa dijadikan signature flavor untuk penetrasi di Depok, karena muncul konsisten di pola perilaku.
"""

# --- Pisahkan data untuk cluster 1 ---
cluster_1 = df[df['kmeans++'] == 1]

# --- Pilih kolom kategorikal ---
kolom_item = ['Jenis Kelamin', 'Kota', 'Promo', 'HariFav', 'FavFlavor']

# --- Bentuk keranjang per pelanggan ---
cluster_1['basket'] = cluster_1[kolom_item].values.tolist()

# --- Transaction Encoder ---
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_ary = te.fit(cluster_1['basket']).transform(cluster_1['basket'])
basket_1 = pd.DataFrame(te_ary, columns=te.columns_)

# --- Apriori dan association rules ---
frequent_1 = apriori(basket_1, min_support=0.05, use_colnames=True)
rules_1 = association_rules(frequent_1, metric="lift", min_threshold=1.1)
strong_rules_1 = rules_1[(rules_1['confidence'] >= 0.5) & (rules_1['lift'] >= 1.2)]

# --- Tampilkan aturan teratas ---
print("🔵 Cluster 1 – Aturan Asosiasi Terkuat:")
display(strong_rules_1.sort_values(by='lift', ascending=False).head(10))

# --- Kesimpulan otomatis ---
def interpret_rules(rules, cluster_name):
    if rules.empty:
        print(f"\n❌ Tidak ditemukan aturan kuat untuk {cluster_name}.")
        return
    print(f"\n📊 Kesimpulan {cluster_name}:")
    for _, row in rules.sort_values(by='lift', ascending=False).head(5).iterrows():
        antecedent = ', '.join(list(row['antecedents']))
        consequent = ', '.join(list(row['consequents']))
        print(f"- Jika pelanggan memiliki atribut [{antecedent}], maka kemungkinan besar juga memiliki [{consequent}] "
              f"(confidence={row['confidence']:.2f}, lift={row['lift']:.2f}).")

interpret_rules(strong_rules_1, "Cluster 1")

"""🧠 Interpretasi:

Pelanggan wanita dari Depok yang jarang menggunakan promo dan berbelanja di hari Minggu sangat identik dengan pembelian rasa Caramel Pecan (premium flavor).

Ini menunjukkan bahwa segmen ini punya loyalitas rasa tinggi dan tidak sensitif harga.

Dengan confidence 1.00, hampir semua pembeli Caramel Pecan di cluster ini memiliki pola perilaku tersebut.

💡 Insight & Rekomendasi Bisnis (Cluster 1):

💎 Premium targeting:
Luncurkan exclusive weekend offers untuk rasa Caramel Pecan, khususnya di Depok.
Contoh: “Sunday Caramel Experience – Limited Edition Flavor for Loyal Customers”

👩 Segmentasi gender-based marketing:
Buat materi promosi yang berkesan elegan dan feminine, karena pelanggan wanita mendominasi segmen ini.

🚫 Minimalkan promo massal.
Mereka bukan pemburu promo, jadi strategi premium branding lebih efektif dibanding diskon besar-besaran.

🕐 Fokus waktu Minggu (weekend habit).
Manfaatkan momentum weekend leisure time untuk meningkatkan penjualan varian premium.
"""

# --- 1. Pisahkan data berdasarkan cluster ---
cluster_3 = df[df['kmeans++'] == 3]

# --- 2. Pilih kolom kategorikal yang akan dianalisis ---
kolom_item = ['Jenis Kelamin', 'Kota', 'Promo', 'HariFav', 'FavFlavor']

# --- 3. Bentuk keranjang per pelanggan (setiap baris = 1 pelanggan) ---
cluster_3['basket'] = cluster_3[kolom_item].values.tolist()

# --- 4. Transaction Encoder (ubah ke format biner True/False) ---
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

def encode_cluster(data):
    te = TransactionEncoder()
    te_ary = te.fit(data['basket']).transform(data['basket'])
    return pd.DataFrame(te_ary, columns=te.columns_)

basket_3 = encode_cluster(cluster_3)

# --- 5. Apriori untuk mencari frequent itemsets ---
frequent_3 = apriori(basket_3, min_support=0.05, use_colnames=True)

# --- 6. Bentuk association rules ---
rules_3 = association_rules(frequent_3, metric="lift", min_threshold=1.1)

# --- 7. Filter aturan yang kuat (eksplorasi awal) ---
strong_rules_3 = rules_3[(rules_3['confidence'] >= 0.5) & (rules_3['lift'] >= 1.2)]

# --- 8. Tampilkan hasil aturan teratas per cluster ---
print("🟢 Cluster 3 – Aturan Asosiasi Terkuat:")
display(strong_rules_3.sort_values(by='lift', ascending=False).head(10))

# --- 9. (Opsional) Buat kesimpulan otomatis sederhana ---
def interpret_rules(rules, cluster_name):
    if rules.empty:
        print(f"\n❌ Tidak ditemukan aturan kuat untuk {cluster_name}.")
        return
    print(f"\n📊 Kesimpulan {cluster_name}:")
    for _, row in rules.sort_values(by='lift', ascending=False).head(5).iterrows():
        antecedent = ', '.join(list(row['antecedents']))
        consequent = ', '.join(list(row['consequents']))
        print(f"- Jika pelanggan memiliki atribut [{antecedent}], maka kemungkinan besar juga memiliki [{consequent}] "
              f"(confidence={row['confidence']:.2f}, lift={row['lift']:.2f}).")

interpret_rules(strong_rules_3, "Cluster 3")

"""🧠 Interpretasi:

Cluster ini menggambarkan dua kelompok perilaku utama dalam satu segmen:

Segmen Pria Jakarta

Pelanggan pria di Jakarta dengan status pengeluaran sedang dan selera Cokelat cenderung bertransaksi pada hari Minggu.

Lift 5.5 menunjukkan hubungan yang kuat dan khas, artinya pola ini tidak terjadi secara kebetulan.

Mereka cenderung menikmati weekend shopping untuk varian rasa klasik (Cokelat), tanpa dorongan promo besar.

Segmen Wanita Tangerang

Pelanggan wanita di Tangerang lebih sering bertransaksi pada hari Sabtu.

Confidence 0.6–0.67 menunjukkan tingkat keajegan yang moderat, tetapi tetap relevan.

Mereka termasuk tipe frequent buyer yang konsisten melakukan pembelian mingguan, kemungkinan karena faktor lokasi (Tangerang sebagai area suburban yang padat keluarga).

💡 Insight & Rekomendasi Bisnis (Cluster 3):

🧋 Cokelat = Rasa Aman untuk Segmen Dewasa.
Gunakan Chocolate Weekend Campaign di Jakarta dengan nuansa keluarga atau nostalgia (“Cokelat klasik untuk momen santai Minggu Anda”).

👨 Fokus pada segmen pria di Jakarta.
Gunakan pendekatan family-oriented atau self-reward marketing (misalnya: “Hadiahkan akhir pekan dengan rasa favorit Anda”).

👩 Perkuat basis pelanggan wanita Tangerang.
Buat promo Sabtu seperti “Saturday Sweet Treat” khusus pelanggan wanita atau keluarga.

🏙️ Ekspansi geografis realistis.
Jakarta dan Tangerang punya potensi besar untuk replikasi strategi weekend sale — cocok untuk scale up di kota besar dengan pola kerja 5 hari (weekday–weekend consumption shift).

# Insight Hasil MBA

💼 Kesimpulan untuk Perusahaan

Hasil analisis menunjukkan bahwa pelanggan memiliki perilaku belanja yang berbeda-beda tergantung pada kota, rasa favorit, dan kebiasaan hari berbelanja. Dari tiga kelompok pelanggan utama yang dianalisis, dapat disimpulkan beberapa peluang penting bagi perusahaan:

1. Pelanggan di Depok menyukai rasa Vanilla dan sering berbelanja pada hari Selasa meskipun jarang menggunakan promo. Ini menunjukkan potensi besar untuk mendorong pembelian melalui promo ringan dan bertema hari tertentu, seperti “Vanilla Tuesday”. Strategi ini dapat meningkatkan partisipasi pelanggan tanpa mengubah kebiasaan belanja mereka yang sudah stabil.

2. Pelanggan wanita di Depok lebih menyukai rasa premium seperti Caramel Pecan dan berbelanja pada akhir pekan, terutama hari Minggu. Mereka tidak terlalu sensitif terhadap harga dan lebih menghargai kualitas serta pengalaman. Karena itu, perusahaan sebaiknya fokus pada strategi branding premium seperti exclusive weekend offers daripada diskon besar-besaran.

3. Pelanggan di Jakarta dan Tangerang memiliki pola belanja akhir pekan yang konsisten, terutama untuk rasa klasik seperti Cokelat. Pria di Jakarta cenderung berbelanja di hari Minggu, sedangkan wanita di Tangerang di hari Sabtu. Ini membuka peluang untuk kampanye akhir pekan berbasis rasa, seperti “Chocolate Weekend Campaign” atau “Saturday Sweet Treat”, yang dapat memperkuat loyalitas pelanggan keluarga dan individu.

Secara keseluruhan, analisis ini menunjukkan bahwa strategi pemasaran yang disesuaikan dengan perilaku dan preferensi pelanggan lebih efektif dibandingkan pendekatan promosi massal.
Perusahaan dapat memanfaatkan insight ini untuk:

- Menentukan lokasi ekspansi prioritas (misalnya Depok dan Tangerang).

- Menyusun strategi promosi spesifik per hari dan rasa.

- Mengembangkan kampanye tematik berbasis segmen pelanggan, agar promosi terasa lebih personal dan relevan.
"""